name: Bug report
description: Something in the game isn't working right
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect instead?
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: PHP Version
      placeholder: e.g. 8.3
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Press '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Screenshots, console errors, etc.
    validations:
      required: false
